### ISSUE TITLE
issue when installing .oiv 

### ISSUE THREAD

**Issue by sinsoft76** [OpenIV-Team/OpenIV-Languages#67]
Hello, 

When I install a .oiv and given the selection between "mods" folder or game folder and I select "mods" folder a pop up window says "install location game folder" and if I select to install in game folder the pop up says "install location mods folder" I think there is an issue with this new message box. It has done it on two different pc's.

**Comment by GooD-NTS** [comment]
Yeah, the dialog was shown incorrect text. It was fixed in the maintenance update  (Build 1031)
